# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bc78cc78f5fba33236f1e314d57974579fa555bf5e6ef2f5074d74e43270a2b47bd050b6f43d23e267a172171333512cc325e4ea2c7854a259588630a37c46c

test:
  secret_key_base: d2aa179a179c1ad8eaaa58831404146252203f2b651ab1b5ca1c24da016f09f62fea11eb2d507f980453069ab4274af7a5f30cb6f46a826055356fd5f858795b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: d2aa179a179c1ad8eaaa58831404146252203f2b651ab1b5ca1c24da016f09f62fea11eb2d507f980453069ab4274af7a5f30cb6f46a826055356fd5f858795b
